#!/usr/bin/env zsh

# Source zshrc to ensure PATH is set correctly
if [ -f ~/.zshrc ]; then
    source ~/.zshrc
fi

# Ejecutar el build
echo "Building the project..."

if ! ./scripts/generate_mocks.sh; then
    echo "Build failed generating mocks."
    exit 1
fi

if ! ./scripts/generate_gql.sh; then
    echo "Build failed generating gql."
    exit 1
fi

if ! ./scripts/generate_doc.sh; then
    echo "Build failed generating docs."
    exit 1
fi

if ! go build ; then
    echo "Build failed building."
    exit 1
fi

rm authgo

# Ejecutar las pruebas
echo "Running tests..."
if ! go test -v ./...; then
    echo "Tests failed. "
    exit 1
fi

./scripts/run_test_report.sh quiet

echo "Build and tests passed. Proceeding with commit."