// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/token/cache.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	token "github.com/nmarsollier/authgo/internal/token"
)

// MockTokenCache is a mock of TokenCache interface.
type MockTokenCache struct {
	ctrl     *gomock.Controller
	recorder *MockTokenCacheMockRecorder
}

// MockTokenCacheMockRecorder is the mock recorder for MockTokenCache.
type MockTokenCacheMockRecorder struct {
	mock *MockTokenCache
}

// NewMockTokenCache creates a new mock instance.
func NewMockTokenCache(ctrl *gomock.Controller) *MockTokenCache {
	mock := &MockTokenCache{ctrl: ctrl}
	mock.recorder = &MockTokenCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenCache) EXPECT() *MockTokenCacheMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTokenCache) Add(token *token.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockTokenCacheMockRecorder) Add(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTokenCache)(nil).Add), token)
}

// Get mocks base method.
func (m *MockTokenCache) Get(tokenString string) (*token.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", tokenString)
	ret0, _ := ret[0].(*token.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTokenCacheMockRecorder) Get(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTokenCache)(nil).Get), tokenString)
}

// Remove mocks base method.
func (m *MockTokenCache) Remove(token string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", token)
}

// Remove indicates an expected call of Remove.
func (mr *MockTokenCacheMockRecorder) Remove(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockTokenCache)(nil).Remove), token)
}
