# Docker para desarrollo
FROM golang:1.14.3-buster

WORKDIR /go/src/github.com/nmarsollier/authgo
COPY . ./
RUN go install

ENV MONGO_URL mongodb://host.docker.internal:27017
ENV RABBIT_URL amqp://host.docker.internal

# Puerto de Image Service
EXPOSE 3001

CMD ["authgo"]

