# Docker produccion o stage
FROM golang:1.22.6-bullseye

WORKDIR /go/src/github.com/nmarsollier/authgo
RUN curl -L https://github.com/nmarsollier/authgo/archive/refs/heads/master.tar.gz | tar xz --strip=1
RUN go install /go/src/github.com/nmarsollier/authgo

ENV MONGO_URL=mongodb://host.docker.internal:27017
ENV RABBIT_URL=amqp://host.docker.internal
ENV FLUENT_URL=host.docker.internal:24224

# Puerto de Auth Service
EXPOSE 3000

CMD ["authgo"]

