package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"

	"github.com/nmarsollier/authgo/graph/model"
	"github.com/nmarsollier/authgo/user"
)

// FindUserResponseByID is the resolver for the findUserResponseByID field.
func (r *entityResolver) FindUserResponseByID(ctx context.Context, id string) (*user.UserResponse, error) {
	panic(fmt.Errorf("not implemented: FindUserResponseByID - findUserResponseByID"))
}

// Entity returns model.EntityResolver implementation.
func (r *Resolver) Entity() model.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
