package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"

	"github.com/99designs/gqlgen/plugin/federation/fedruntime"
	"github.com/nmarsollier/authgo/graph/model"
	"github.com/nmarsollier/authgo/graph/resolvers"
	"github.com/nmarsollier/authgo/user"
)

// FindUserDataByID is the resolver for the findUserDataByID field.
func (r *entityResolver) FindUserDataByID(ctx context.Context, id string) (*user.UserData, error) {
	user, err := resolvers.FindUser(ctx, id)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// Entity returns model.EntityResolver implementation.
func (r *Resolver) Entity() model.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }

var _ fedruntime.Entity = &user.UserData{}
