basePath: /v1
definitions:
  errs.ValidationErr:
    properties:
      messages:
        items:
          $ref: '#/definitions/errs.errField'
        type: array
    type: object
  errs.errField:
    properties:
      message:
        type: string
      path:
        type: string
    type: object
  rest.changePasswordBody:
    properties:
      currentPassword:
        maxLength: 100
        minLength: 1
        type: string
      newPassword:
        maxLength: 100
        minLength: 1
        type: string
    required:
    - currentPassword
    - newPassword
    type: object
  rest.grantPermissionBody:
    properties:
      permissions:
        items:
          type: string
        type: array
    required:
    - permissions
    type: object
  rst.ErrorData:
    properties:
      error:
        type: string
    type: object
  usecases.SignInRequest:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  usecases.SignUpRequest:
    properties:
      login:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - login
    - name
    - password
    type: object
  usecases.TokenResponse:
    properties:
      token:
        type: string
    type: object
  user.UserData:
    properties:
      enabled:
        type: boolean
      id:
        type: string
      login:
        type: string
      name:
        type: string
      permissions:
        items:
          type: string
        type: array
    type: object
host: localhost:3000
info:
  contact:
    email: nmarsollier@gmail.com
    name: Nestor Marsollier
  description: Microservicio de Autentificaci칩n.
  title: AuthGo
  version: "1.0"
paths:
  /users/:userID/grant:
    post:
      consumes:
      - application/json
      description: Otorga permisos al usuario indicado, el usuario logueado tiene
        que tener permiso "admin".
      parameters:
      - description: ID del usuario a habilitar permiso
        in: path
        name: userId
        required: true
        type: string
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: Permisos a Habilitar
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/rest.grantPermissionBody'
      produces:
      - application/json
      responses:
        "200":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rst.ErrorData'
      summary: Haiblitar permisos
      tags:
      - Seguridad
  /users/:userID/revoke:
    post:
      consumes:
      - application/json
      description: Quita permisos al usuario indicado, el usuario logueado tiene que
        tener permiso "admin".
      parameters:
      - description: ID del usuario a quitar permiso
        in: path
        name: userId
        required: true
        type: string
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: Permisos a Qutiar
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/rest.grantPermissionBody'
      produces:
      - application/json
      responses:
        "200":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rst.ErrorData'
      summary: Quitar permisos
      tags:
      - Seguridad
  /users/:userId/disable:
    post:
      consumes:
      - application/json
      description: Deshabilita un usuario en el sistema. El usuario logueado debe
        tener permisos "admin".
      parameters:
      - description: ID del usuario a deshabilitar
        in: path
        name: userId
        required: true
        type: string
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rst.ErrorData'
      summary: Deshabilitar Usuario
      tags:
      - Seguridad
  /users/:userId/enable:
    post:
      consumes:
      - application/json
      description: Habilita un usuario en el sistema. El usuario logueado debe tener
        permisos "admin".
      parameters:
      - description: ID del usuario a habilitar
        in: path
        name: userId
        required: true
        type: string
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rst.ErrorData'
      summary: Enable User
      tags:
      - Seguridad
  /users/all:
    get:
      consumes:
      - application/json
      description: Obtiene informaci칩n de todos los usuarios. El usuario logueado
        debe tener permisos "admin".
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Users
          schema:
            items:
              $ref: '#/definitions/user.UserData'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rst.ErrorData'
      summary: Listar Usuarios
      tags:
      - Seguridad
  /users/current:
    get:
      consumes:
      - application/json
      description: Obtiene informaci칩n del usuario actual.
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User data
          schema:
            $ref: '#/definitions/user.UserData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rst.ErrorData'
      summary: Usuario Actual
      tags:
      - Seguridad
  /users/password:
    post:
      consumes:
      - application/json
      description: Cambia la contrase침a del usuario actual.
      parameters:
      - description: Passwords
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/rest.changePasswordBody'
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rst.ErrorData'
      summary: Cambiar Password
      tags:
      - Seguridad
  /users/signin:
    post:
      consumes:
      - application/json
      description: Loguea un usuario en el sistema.
      parameters:
      - description: Sign in information
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/usecases.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User Token
          schema:
            $ref: '#/definitions/usecases.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rst.ErrorData'
      summary: Login
      tags:
      - Seguridad
  /users/signout:
    get:
      consumes:
      - application/json
      description: Desloguea un usuario en el sistema, invalida el token.
      parameters:
      - description: Bearer {token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: No Content
        "500":
          description: Error response
          schema:
            $ref: '#/definitions/rst.ErrorData'
      summary: Logout
      tags:
      - Seguridad
  /users/signup:
    post:
      consumes:
      - application/json
      description: Registra un nuevo usuario en el sistema.
      parameters:
      - description: Informacion de ususario
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/usecases.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User Token
          schema:
            $ref: '#/definitions/usecases.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errs.ValidationErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rst.ErrorData'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rst.ErrorData'
      summary: Registrar Usuario
      tags:
      - Seguridad
swagger: "2.0"
